#!/usr/bin/python3
#SPDX-FileCopyrightText: 2024 Tomoyuki Sekiguchi
#SPDX-Lincense-Identifier: GPL-3.0-only
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

if 

print(ans)
